paths:
  uploads: public
  static: public
collections_config:
  public:
    path: public
    name: Kites Website
    icon:
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  main_image:
    type: image
    cascade: true
  secondary_image:
    type: image
    cascade: true
  extra_image:
    type: image
    cascade: true
  notation_image:
    type: image
    cascade: true
  bio_image:
    type: image
    cascade: true
  gallery_images:
    type: array
    cascade: true
    of:
      type: image
  header_images:
    type: array
    cascade: true
    of:
      type: image
  comparison_images:
    type: array
    cascade: true
    of:
      type: image
  gallery:
    type: array
    cascade: true
    of:
      type: image
  gallery_vertical:
    type: array
    cascade: true
    of:
      type: image
  text_1:
    type: textarea
    cascade: true
  text_2:
    type: textarea
    cascade: true
  text_3:
    type: textarea
    cascade: true
  description:
    type: textarea
    cascade: true
  intro_text:
    type: textarea
    cascade: true
  bio_text:
    type: textarea
    cascade: true
  materials:
    type: textarea
    cascade: true
data_config:
  content:
    path: public/content.json
timezone: Asia/Tokyo
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
